# Generated by Django 5.2.5 on 2025-09-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notetag_alter_note_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteVersion',
        ),
    ]
