# Generated by Django 5.2.5 on 2025-09-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_delete_noteversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_saved_by',
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(default='acsdc.jpg', upload_to='attachments/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
