# Generated by Django 5.2.5 on 2025-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_is_archived_remove_note_last_saved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/'),
        ),
    ]
